//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class DealerInventory
    {
        public int DlrInvID { get; set; }
        public Nullable<int> Make { get; set; }
        public Nullable<int> Model { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<int> Miles { get; set; }
        public Nullable<int> ColorID { get; set; }
        public Nullable<int> DealerID { get; set; }
        public string pic { get; set; }
    
        public virtual Color Color { get; set; }
        public virtual Dealer Dealer { get; set; }
        public virtual Make Make1 { get; set; }
        public virtual Model Model1 { get; set; }
    }
}
